# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: homepage, action: index }

logins:
  url:   /logins
  param: { module: logins, action: loginForm }

search:
  url:   /search
  param: { module: search, action: index }

search_result:
  url:   /search_result
  param: { module: search, action: searchResult }

search_page:
  url:   /search_page/:page
  param: { module: search, action: searchResult }

google_response:
  url: /google_response/*
  param: {module: logins, action: googleResponse}

twitter_response:
  url: /twitter_response/*
  param: {module: logins, action: twitterResponse}

facebook_response:
  url: /facebook_response/*
  param: {module: logins, action: facebookResponse}

#twitter_login:
#  url: /twitter_login
#  param: {module: sfTwitterAuth, action: login}
#
#facebook_login:
#  url: /facebook_login
#  param: {module: sfFacebookConnectAuth, action: signin}

#sf_guard_signin:
#  url:   /login
#  param: { module: sfGuardAuth, action: signin }
#
#sf_guard_signout:
#  url:   /logout
#  param: { module: sfGuardAuth, action: signout }

default:
  url:   /:module/:action/*