propel:

  wines:
    id:                         ~
    user_id:                    { type: integer, required: true, foreignTable: sf_guard_user, foreignReference: id, onDelete: cascade }
    lable:                      { type: varchar, size: 255 }
    picture:                    { type: varchar, size: 255 }
    description:                { type: longvarchar }
    
  wine_property_name:
    id:                         ~
    name:                       { type: varchar, size: 255 }
    description:                { type: longvarchar }

  wine_property_value:
    id:                         ~
    property_id:                { type: integer, required: true, foreignTable: wine_property_name, foreignReference: id, onDelete: cascade }
    name:                       { type: varchar, size: 255 }

  wine_properties:
    wine_id:                    { type: integer, required: true, foreignTable: wines, foreignReference: id, onDelete: cascade }
    wine_property_value_id:     { type: integer, required: true, foreignTable: wine_property_value, foreignReference: id, onDelete: cascade }