generator:
  class: sfPropelGenerator
  param:
    model_class:           WinePropertyName
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              WinePropertyName
    plural:                WinePropertyNames
    route_prefix:          wine_property_name
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
